from rest_framework import viewsets, permissions, status
from rest_framework.views import APIView
from rest_framework.response import Response
from .models import Ticket, TicketLog, IncidentAuditLog, MileageReport
from .serializers import TicketSerializer, LegacyTicketSerializer, MileageReportSerializer
import logging

audit_logger = logging.getLogger('ticket_audit')

# Source → human label mapping for audit log messages
SOURCE_LABELS = {
    'firewall':   'Firewall Service',
    'antivirus':  'Antivirus Service',
    'network':    'Network Monitoring Service',
    'monitoring': 'External Monitoring API',
    'employee':   'Employee Report',
}


class IsManager(permissions.BasePermission):
    def has_permission(self, request, view):
        return request.user.is_authenticated and (request.user.role == 'manager' or request.user.is_superuser)

class TicketViewSet(viewsets.ModelViewSet):
    serializer_class = LegacyTicketSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        user = self.request.user
        if user.role == 'manager' or user.is_superuser:
            return Ticket.objects.all()
        return Ticket.objects.filter(created_by=user)

    def perform_create(self, serializer):
        serializer.save(created_by=self.request.user)

    def get_permissions(self):
        if self.action in ['update', 'partial_update', 'destroy']:
            return [IsManager()]
        return super().get_permissions()


class APITicketListView(APIView):
    permission_classes = [permissions.IsAuthenticated]

    def get(self, request):
        if request.user.role == 'manager' or request.user.is_superuser:
            tickets = Ticket.objects.all()
        else:
            tickets = Ticket.objects.filter(created_by=request.user)
        serializer = TicketSerializer(tickets, many=True)
        return Response(serializer.data)


class APITicketCreateView(APIView):
    permission_classes = [permissions.IsAuthenticated]

    def post(self, request):
        title       = request.data.get('title')
        description = request.data.get('description')
        ticket_type = request.data.get('ticket_type')
        priority    = request.data.get('priority')
        source      = request.data.get('source', 'monitoring')

        if not all([title, description, ticket_type, priority]):
            return Response(
                {"error": "All fields (title, description, ticket_type, priority) are required."},
                status=status.HTTP_400_BAD_REQUEST
            )

        if ticket_type == 'Security Incident' and priority == 'Low':
            return Response(
                {"error": "Priority cannot be 'Low' for a Security Incident."},
                status=status.HTTP_400_BAD_REQUEST
            )

        # Validate source
        valid_sources = [s[0] for s in Ticket.SOURCE_CHOICES]
        if source not in valid_sources:
            source = 'monitoring'

        # Check for unique title per user constraint
        if Ticket.objects.filter(created_by=request.user, title=title).exists():
            return Response(
                {"error": "You have already created a ticket with this title."},
                status=status.HTTP_400_BAD_REQUEST
            )

        ticket = Ticket.objects.create(
            title=title,
            description=description,
            ticket_type=ticket_type,
            priority=priority,
            source=source,
            nist_stage='detection',
            created_by=request.user,
        )

        actor_label = SOURCE_LABELS.get(source, 'External Monitoring API')

        # Rich incident audit log entry
        IncidentAuditLog.objects.create(
            ticket=ticket,
            actor=None,
            actor_label=actor_label,
            action=f"Incident automatically generated by {actor_label} via JWT API.",
        )

        # Chain-of-custody database log
        TicketLog.objects.create(
            ticket=ticket,
            changed_by=request.user,
            change_description=f"Ticket created via JWT API. Source: {actor_label}. Type: {ticket_type}, Priority: {priority}",
        )

        # File-based audit log
        audit_logger.info("", extra={
            'user': request.user.email,
            'action': 'API_CREATE',
            'id': ticket.id,
            'detail': f"Ticket created via JWT API. Source: {source}, Type: {ticket_type}, Priority: {priority}",
        })

        return Response({
            "ticket_id": ticket.id,
            "title": ticket.title,
            "source": ticket.get_source_display(),
            "nist_stage": ticket.nist_stage,
            "created_at": ticket.created_at,
        }, status=status.HTTP_201_CREATED)


class MileageReportViewSet(viewsets.ModelViewSet):
    serializer_class = MileageReportSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        user = self.request.user
        if user.role == 'manager' or user.is_superuser:
            return MileageReport.objects.all()
        return MileageReport.objects.filter(driver=user)

    def perform_create(self, serializer):
        serializer.save(driver=self.request.user)
