# Generated by Django 6.0.5 on 2026-05-31 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityreport',
            name='status',
            field=models.CharField(choices=[('Preparation', 'Preparation'), ('Detection', 'Detection'), ('Containment', 'Containment'), ('Recovery', 'Recovery')], default='Preparation', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Preparation', 'Preparation'), ('Detection', 'Detection'), ('Containment', 'Containment'), ('Recovery', 'Recovery')], default='Preparation', max_length=20),
        ),
    ]
