# Generated by Django 6.0.5 on 2026-06-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_alter_securityreport_status_alter_ticket_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('primary', 'Primary / Info'), ('warning', 'Warning / Alert'), ('success', 'Success / Good News'), ('danger', 'Danger / Critical')], default='primary', max_length=20)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.CharField(max_length=255, verbose_name='Question')),
                ('a', models.TextField(verbose_name='Answer')),
                ('steps', models.TextField(blank=True, help_text='Enter resolution steps separated by a newline', null=True)),
                ('icon', models.CharField(default='fa-circle-question text-primary', help_text="FontAwesome classes, e.g., 'fa-circle-question text-primary'", max_length=50)),
                ('keywords', models.CharField(blank=True, help_text='Keywords for search filtering', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='securityreport',
            name='report_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
