# Generated by Django 6.0.5 on 2026-06-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0004_announcement_faq_alter_securityreport_report_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityreport',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
