# Generated by Django 6.0.5 on 2026-06-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0007_ticketupdate_remove_activitylog_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notify_security',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_tickets',
            field=models.BooleanField(default=True),
        ),
    ]
