# Generated by Django 6.0.5 on 2026-06-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0011_alter_customuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('title', 'created_by')},
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['nist_stage'], name='helpdesk_ti_nist_st_e5066d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_by'], name='helpdesk_ti_created_9fad04_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['is_resolved'], name='helpdesk_ti_is_reso_4c0d79_idx'),
        ),
    ]
