# Generated by Django 6.0.5 on 2026-06-03 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0012_alter_ticket_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='source',
            field=models.CharField(choices=[('employee', 'Employee Report'), ('firewall', 'Firewall Alert'), ('antivirus', 'Antivirus Alert'), ('network', 'Network Monitor'), ('monitoring', 'Security Monitoring Tool')], default='employee', max_length=20),
        ),
        migrations.CreateModel(
            name='IncidentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(blank=True, help_text="Human-readable actor name, e.g. 'Firewall Service' or 'IT Manager Alice'", max_length=200)),
                ('action', models.TextField(help_text='Human-readable description of what happened')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='helpdesk.ticket')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
