# Generated by Django 6.0.5 on 2026-06-04 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0013_ticket_source_incidentauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MileageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dashboard_alert', models.TextField(blank=True, default='')),
                ('fleet_valuation', models.DecimalField(decimal_places=2, default=1250000.0, max_digits=15)),
                ('procurement_cost', models.DecimalField(decimal_places=2, default=45000.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mileage_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
